### ISSUE TITLE
Dropdown not visible in IBP on mobile

### ISSUE THREAD

**Issue by antonseb** [sebgroup/green#639] opened 2022-11-04 09:45 UTC
We're using scoped css (use-green) on our react MFE on IBP, and when you click the dropdown-button on mobile it appears at the bottom of the screen, hidden behind the mobile browser menu. 

MFE: https://apps.tst.sebank.se/cps/ibp/wow/3000/3500/wow3564.aspx?context=ibp

![image](https://user-images.githubusercontent.com/117288898/199942668-7d1d5575-50bc-4151-aa64-152c5f6f32ef.png)

**Comment by splashdust** [comment] 2022-11-15 15:03
@antonseb The problem appears to be that your application is running in an iframe that is much higher than the viewport. The dropdown menu appears at the bottom of of its context viewport (since it has `position: fixed; bottom: 0;`), which in this case ends up being outside the screen due to the height of the iframe.

I'm not sure if you have any influence over the styling of the iframe, but if you do, try to make sure the iframe is never higher than the device viewport by adding `max-height: 100vh`.

Otherwise, a solution could be to add custom styling to the dropdown menu itself. For example:
```css
._popover.active {
  position: static;
}
```
This will make it appear statically below the dropdown button, pushing everything else down.

**Comment by vsjolander** [comment] 2022-11-15 15:20
I'm not sure why the dropdown has this design. I can't find it in Figma.

Will check with designers regarding this current design and see if we it should be changed to a "normal dropdown".

This would solve the problem we have with tall iFrames.

**Comment by JohanObrink** [comment] 2022-11-16 08:11
@vsjolander The reasoning behind placing selections at the bottom of the screen is that that's where the thumb is. The same goes for activity panel and, lately, the address bar in Safari. It's just better usability.

**Comment by vsjolander** [comment] 2022-11-16 20:28
@JohanObrink isn't the thumb by the dropdown button/trigger since you just pressed it? I can also see usability issues if the listbox is long. Maybe a native select element would be to prefer as it's more accessible in general (it can overlay the address bar on ios i realized now).

IOS also moved to a more traditional dropdown list box for select elements form the spinning wheel stuff they had going before.

Anyways... we don't have this slide-up designed or documented anywhere for dropdown so we should bring this up at a Green coaching! You should join and advocate you case 😃

**Comment by JohanObrink** [comment] 2022-11-17 12:02
@vsjolander I don't care enough to argue anything. This was a discussion lead by Robert at the time of implementing it. I am happy eiother way 😄 

So if changing the behaviour fixes the current *situation* in IFrame settings, maybe we should just go traditional for now and re-open the discussion later on?

**Comment by splashdust** [comment] 2022-11-18 13:04
@vsjolander @JohanObrink There is a design spec in DL actually, but it's under "Fold-out": https://designlibrary.sebgroup.com/components/component-foldout

I remember that we had discussions around this early on, where we determined that the drop-down and fold-out designs are very similar in appearance, and so they should be implemented as a single component for both use cases.

That conclusion may have been flawed from an accessibility perspective though. Even though they look similar, we probably still need to differentiate between dropdowns used for data entry in a form and dropdowns used as menus for selecting an action.

**Comment by daneriseb** [comment] 2023-01-20 10:07
This issue seems to be fixed now, I can't reproduce it anymore.

**Closed** 2023-01-26 17:47 UTC
Labels: Type: Bug, Priority: High
