### ISSUE TITLE
Button/Tab styling: all borders are rounded

### ISSUE THREAD

**Issue by vizorian** [sebgroup/green#1155] opened 2024-01-10 08:54 UTC
### Description

There is an issue where all the borders are rounded for button tabs, making them look weird:
![image](https://github.com/sebgroup/green/assets/14858098/602f2bc7-5481-4887-84bb-62d46baaf5a3)

It's done in `use-green` for React:
![image](https://github.com/sebgroup/green/assets/14858098/a485b9a2-8330-42ee-ae6e-f8a9d1e3241c)
`.use-green{ --sg-border-radius: 4px; }`

Would it not be better to have only the outer borders rounded, e.g. `border-radius: 4px 4px 0 0`?
![image](https://github.com/sebgroup/green/assets/14858098/ab9e1e1f-13a3-4aa8-a481-096dfebb8027)

This would remove the need to place an `!important` to override this.

### Who will benefit from this feature?

Leasing team & anyone else who uses Tabs styling.

**Comment by splashdust** [comment] 2024-01-10 11:09
Hi @vizorian, I suspect the issue is that the wrong markup is used for the tabs, which causes incorrect style to be applied.

From what I can see, the tabs in Storybook looks correct. Check here, and have a look at the markup for reference:
https://sebgroup.github.io/green/latest/chlorophyll/?path=/docs/components-tabs--tabs

I will close this issue since it does not appear to be an issue with the framework itself, but feel free to re-open if you think this is wrong!

**Closed by splashdust** 2024-01-10 11:09 UTC
Labels: Type: Feature request
