### ISSUE TITLE
Datepicker select month from dropdown not works

### ISSUE THREAD

**Issue by GomathiDevarajan** [sebgroup/green#898] opened 2023-05-22 19:26 UTC
### Bug already reported ?

- [X] I confirm that I have checked if the bug already has been reported

### For which framework/library you are reporting the bug

React

### Component name

Datepicker

### Description

From the default Datepicker months dropdown choose any other month and select any date, it always sets month value to the current month (or month selected using '>' icon).

For ex:
1. First select any date from current month ex: 2023-05-22
2. Open datepicker again and choose any other month from dropdown ex: July
3. select any date from July ex: 15
4. Datepicker value will be set to 2023-05-15 instead of 2023-07-15
5. 
![image](https://github.com/sebgroup/green/assets/134276747/bb010da4-e6ea-49be-847f-f3323e1f35cd)

**Comment by splashdust** [comment] 2023-05-24 07:08
Duplicate of #881

**Comment by splashdust** [comment] 2023-05-24 07:09
Duplicate of #840

**Closed** 2023-05-24 07:49 UTC
Labels: Type: Bug, Comp: Datepicker
