### ISSUE TITLE
NumberInput: Support for showing a unit inside the field

### ISSUE THREAD

**Issue by daneriseb** [sebgroup/green#873] opened 2023-05-08 09:03 UTC
### Does the component already exist

- [X] I confirm that I have checked if the component already exists in any of the Green libraries

### For which framework/library you are requesting the component

React

### Description

Support for showing a unit inside the field.
Similar to https://github.com/sebgroup/green/issues/819 but for NumberInput.

**Comment by vsjolander** [comment] 2023-10-23 13:13
duplicate of #910

**Closed** 2023-11-30 11:24 UTC
Labels: Comp: Input
